module.exports = [
"[project]/.next-internal/server/app/dashboard/page/actions.js [app-rsc] (server actions loader, ecmascript)", ((__turbopack_context__, module, exports) => {

}),
"[project]/src/app/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)", ((__turbopack_context__) => {

__turbopack_context__.n(__turbopack_context__.i("[project]/src/app/layout.tsx [app-rsc] (ecmascript)"));
}),
"[project]/src/app/loading.tsx [app-rsc] (ecmascript, Next.js Server Component)", ((__turbopack_context__) => {

__turbopack_context__.n(__turbopack_context__.i("[project]/src/app/loading.tsx [app-rsc] (ecmascript)"));
}),
"[project]/src/app/not-found.tsx [app-rsc] (ecmascript, Next.js Server Component)", ((__turbopack_context__) => {

__turbopack_context__.n(__turbopack_context__.i("[project]/src/app/not-found.tsx [app-rsc] (ecmascript)"));
}),
"[project]/src/app/dashboard/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)", ((__turbopack_context__) => {

__turbopack_context__.n(__turbopack_context__.i("[project]/src/app/dashboard/layout.tsx [app-rsc] (ecmascript)"));
}),
"[project]/src/components/dashboard/dashboard-home-screen.tsx [app-rsc] (client reference proxy) <module evaluation>", ((__turbopack_context__) => {
"use strict";

// This file is generated by next-core EcmascriptClientReferenceModule.
__turbopack_context__.s([
    "default",
    ()=>__TURBOPACK__default__export__
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const __TURBOPACK__default__export__ = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call the default export of [project]/src/components/dashboard/dashboard-home-screen.tsx <module evaluation> from the server, but it's on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/src/components/dashboard/dashboard-home-screen.tsx <module evaluation>", "default");
}),
"[project]/src/components/dashboard/dashboard-home-screen.tsx [app-rsc] (client reference proxy)", ((__turbopack_context__) => {
"use strict";

// This file is generated by next-core EcmascriptClientReferenceModule.
__turbopack_context__.s([
    "default",
    ()=>__TURBOPACK__default__export__
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const __TURBOPACK__default__export__ = (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call the default export of [project]/src/components/dashboard/dashboard-home-screen.tsx from the server, but it's on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/src/components/dashboard/dashboard-home-screen.tsx", "default");
}),
"[project]/src/components/dashboard/dashboard-home-screen.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$dashboard$2f$dashboard$2d$home$2d$screen$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__$3c$module__evaluation$3e$__ = __turbopack_context__.i("[project]/src/components/dashboard/dashboard-home-screen.tsx [app-rsc] (client reference proxy) <module evaluation>");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$dashboard$2f$dashboard$2d$home$2d$screen$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__ = __turbopack_context__.i("[project]/src/components/dashboard/dashboard-home-screen.tsx [app-rsc] (client reference proxy)");
;
__turbopack_context__.n(__TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$dashboard$2f$dashboard$2d$home$2d$screen$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__);
}),
"[project]/src/lib/assistant-categories.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "getAssistantQuickStartMessage",
    ()=>getAssistantQuickStartMessage,
    "isAssistantIncidentCategory",
    ()=>isAssistantIncidentCategory
]);
function isAssistantIncidentCategory(value) {
    return value === "domestic_violence" || value === "racial_abuse" || value === "migrant_challenges" || value === "cyber_scam";
}
function getAssistantQuickStartMessage(category) {
    switch(category){
        case "domestic_violence":
            return "I need help related to domestic violence and want guidance on what to do next.";
        case "racial_abuse":
            return "I want help reporting racial abuse and understanding the safest next steps.";
        case "migrant_challenges":
            return "I need support with a migrant-related challenge and want guidance I can understand clearly.";
        case "cyber_scam":
            return "I think I may be dealing with a cyber scam and need help assessing it.";
    }
}
}),
"[project]/src/lib/dashboard-card-flows.ts [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "getDashboardActionHref",
    ()=>getDashboardActionHref,
    "getDashboardAssistantEntryHref",
    ()=>getDashboardAssistantEntryHref,
    "getDashboardAssistantTopicChips",
    ()=>getDashboardAssistantTopicChips,
    "getDashboardCardEntryHref",
    ()=>getDashboardCardEntryHref,
    "getDashboardCardFlow",
    ()=>getDashboardCardFlow,
    "isDashboardCardFlowId",
    ()=>isDashboardCardFlowId
]);
const dashboardCardFlows = {
    domestic_violence: {
        id: "domestic_violence",
        title: "Domestic Violence",
        categoryKey: "domestic_violence",
        flowType: "safety_support_report",
        targetView: "assistant",
        starterPrompt: "I may be experiencing domestic or family violence and I want to understand safe options.",
        safetyLevel: "high",
        nextActions: [
            {
                id: "start_report",
                label: "Start a safe report",
                description: "Open the report flow with domestic violence context."
            },
            {
                id: "find_support",
                label: "Find support services",
                description: "Browse support services with domestic violence context."
            },
            {
                id: "safety_plan",
                label: "Create safety plan",
                description: "Go to support guidance with safety planning focus."
            },
            {
                id: "talk_with_assistant",
                label: "Talk with SafeSpeak",
                description: "Start a guided assistant conversation with this topic."
            },
            {
                id: "quick_exit",
                label: "Use Quick Exit",
                description: "Leave the page immediately if it is not safe to continue."
            }
        ],
        disclaimers: [
            "SafeSpeak is not a crisis service.",
            "If you are in immediate danger, call 000.",
            "If it is safe, contact 1800RESPECT.",
            "This information is general information only."
        ]
    },
    racial_abuse: {
        id: "racial_abuse",
        title: "Racial Abuse",
        categoryKey: "racial_abuse",
        flowType: "report_guidance",
        targetView: "assistant",
        starterPrompt: "I experienced racial abuse and want to understand my options safely.",
        safetyLevel: "medium",
        nextActions: [
            {
                id: "start_report",
                label: "Start incident report",
                description: "Open the report flow with racial abuse context."
            },
            {
                id: "understand_reporting_options",
                label: "Understand reporting options",
                description: "Open guided reporting options with SafeSpeak."
            },
            {
                id: "find_support",
                label: "Find support",
                description: "Browse support services and community support options."
            },
            {
                id: "save_evidence",
                label: "Save evidence",
                description: "Go to the evidence step with this topic in context."
            },
            {
                id: "talk_with_assistant",
                label: "Talk with SafeSpeak",
                description: "Start a guided assistant conversation with this topic."
            }
        ],
        disclaimers: [
            "This information is general information only."
        ]
    },
    cyber_scam: {
        id: "cyber_scam",
        title: "Cyber Scam",
        categoryKey: "cyber_scam",
        flowType: "scam_analysis",
        targetView: "scamshieldintake",
        starterPrompt: "I think I may be dealing with a cyber scam and need help assessing it.",
        safetyLevel: "medium",
        nextActions: [],
        disclaimers: [
            "Analysis starts only after you submit content for review."
        ]
    },
    migrant_challenges: {
        id: "migrant_challenges",
        title: "Migrant Challenges",
        categoryKey: "migrant_challenges",
        flowType: "support_guidance",
        targetView: "assistant",
        starterPrompt: "I am facing migrant-related challenges and want safe, culturally appropriate guidance.",
        safetyLevel: "medium",
        nextActions: [
            {
                id: "find_support",
                label: "Find migrant support services",
                description: "Browse support services with migrant support context."
            },
            {
                id: "understand_reporting_options",
                label: "Understand workplace/housing/school options",
                description: "Start a guided options conversation for this topic."
            },
            {
                id: "interpreter_guidance",
                label: "Ask for interpreter guidance",
                description: "Open support with interpreter and access needs in mind."
            },
            {
                id: "start_report",
                label: "Start a report",
                description: "Open the report flow with migrant challenge context."
            },
            {
                id: "talk_with_assistant",
                label: "Talk with SafeSpeak",
                description: "Start a guided assistant conversation with this topic."
            }
        ],
        disclaimers: [
            "This information is general information only."
        ]
    },
    general_assistant: {
        id: "general_assistant",
        title: "Let’s talk with SafeSpeak",
        categoryKey: "general_assistant",
        flowType: "general_assistant",
        targetView: "assistant",
        safetyLevel: "medium",
        nextActions: [],
        disclaimers: [
            "Choose a topic or start in general conversation."
        ]
    },
    scamshield: {
        id: "scamshield",
        title: "ScamShield",
        categoryKey: "cyber_scam",
        flowType: "scam_analysis",
        targetView: "scamshieldintake",
        starterPrompt: "I think I may be dealing with a cyber scam and need help assessing it.",
        safetyLevel: "medium",
        nextActions: [],
        disclaimers: [
            "Analysis starts only after you submit content for review."
        ]
    },
    resources: {
        id: "resources",
        title: "Resources",
        flowType: "learning",
        targetView: "resources",
        safetyLevel: "low",
        nextActions: [],
        disclaimers: [
            "Browse learning resources without starting an AI or report flow."
        ]
    },
    local_intelligence: {
        id: "local_intelligence",
        title: "Local Intelligence",
        flowType: "learning",
        targetView: "localintelligence",
        safetyLevel: "low",
        nextActions: [],
        disclaimers: []
    },
    micro_cards: {
        id: "micro_cards",
        title: "Micro-Cards",
        flowType: "learning",
        targetView: "microcards",
        safetyLevel: "low",
        nextActions: [],
        disclaimers: []
    },
    workplace_issue: {
        id: "workplace_issue",
        title: "Workplace Issue",
        flowType: "general_assistant",
        targetView: "assistantconversation",
        starterPrompt: "I am dealing with a workplace issue and want to understand safe next steps.",
        safetyLevel: "medium",
        nextActions: [],
        disclaimers: [
            "This information is general information only."
        ]
    },
    school_issue: {
        id: "school_issue",
        title: "School Issue",
        flowType: "general_assistant",
        targetView: "assistantconversation",
        starterPrompt: "I am dealing with a school-related issue and want to understand safe next steps.",
        safetyLevel: "medium",
        nextActions: [],
        disclaimers: [
            "This information is general information only."
        ]
    },
    online_abuse: {
        id: "online_abuse",
        title: "Online Abuse",
        flowType: "general_assistant",
        targetView: "assistantconversation",
        starterPrompt: "I am experiencing online abuse and want to understand safe options.",
        safetyLevel: "medium",
        nextActions: [],
        disclaimers: [
            "This information is general information only."
        ]
    },
    other: {
        id: "other",
        title: "Other",
        flowType: "general_assistant",
        targetView: "assistantconversation",
        starterPrompt: "Something happened and I want help understanding my options safely.",
        safetyLevel: "medium",
        nextActions: [],
        disclaimers: [
            "This information is general information only."
        ]
    }
};
const supportedFlowIds = Object.keys(dashboardCardFlows);
function isDashboardCardFlowId(value) {
    return Boolean(value && supportedFlowIds.includes(value));
}
function getDashboardCardFlow(id) {
    return dashboardCardFlows[id];
}
function getDashboardAssistantTopicChips() {
    return [
        dashboardCardFlows.domestic_violence,
        dashboardCardFlows.racial_abuse,
        dashboardCardFlows.cyber_scam,
        dashboardCardFlows.migrant_challenges,
        dashboardCardFlows.workplace_issue,
        dashboardCardFlows.school_issue,
        dashboardCardFlows.online_abuse,
        dashboardCardFlows.other
    ];
}
function getDashboardCardEntryHref(id) {
    const flow = getDashboardCardFlow(id);
    if (flow.targetView === "scamshieldintake") {
        return {
            pathname: "/dashboard",
            query: {
                view: "scamshieldintake",
                topic: flow.id,
                category: flow.categoryKey === "cyber_scam" ? "cyber_scam" : undefined
            }
        };
    }
    if (flow.targetView === "microeducation") {
        return {
            pathname: "/dashboard",
            query: {
                view: "microeducation",
                topic: flow.id
            }
        };
    }
    if (flow.targetView === "resources") {
        return {
            pathname: "/dashboard",
            query: {
                view: "resources",
                topic: flow.id
            }
        };
    }
    if (flow.targetView === "localintelligence") {
        return {
            pathname: "/dashboard",
            query: {
                view: "localintelligence",
                topic: flow.id
            }
        };
    }
    if (flow.targetView === "microcards") {
        return {
            pathname: "/dashboard",
            query: {
                view: "microcards",
                topic: flow.id
            }
        };
    }
    return {
        pathname: "/dashboard",
        query: {
            view: "assistant",
            topic: flow.id,
            category: flow.categoryKey && flow.categoryKey !== "general_assistant" ? flow.categoryKey : undefined
        }
    };
}
function getDashboardAssistantEntryHref(id) {
    return {
        pathname: "/dashboard",
        query: {
            view: "assistant",
            topic: id
        }
    };
}
function getDashboardActionHref(flowId, actionId) {
    const flow = getDashboardCardFlow(flowId);
    const category = flow.categoryKey && flow.categoryKey !== "general_assistant" ? flow.categoryKey : undefined;
    const message = flow.starterPrompt;
    switch(actionId){
        case "start_report":
            return {
                pathname: "/dashboard",
                query: {
                    view: "reportsubmissiondetails",
                    topic: flow.id,
                    category,
                    message
                }
            };
        case "find_support":
            return {
                pathname: "/dashboard/explorer",
                query: {
                    category,
                    topic: flow.id
                }
            };
        case "safety_plan":
            return {
                pathname: "/dashboard/explorer",
                query: {
                    category,
                    topic: flow.id,
                    focus: "safety_plan"
                }
            };
        case "talk_with_assistant":
            return {
                pathname: "/dashboard",
                query: {
                    view: "assistantconversation",
                    topic: flow.id,
                    category,
                    prefillMessage: message
                }
            };
        case "understand_reporting_options":
            return {
                pathname: "/dashboard",
                query: {
                    view: "assistantconversation",
                    topic: flow.id,
                    category,
                    prefillMessage: flowId === "racial_abuse" ? "I want to understand my safe reporting options after racial abuse." : flowId === "migrant_challenges" ? "I want to understand my workplace, housing, or school options safely." : message
                }
            };
        case "save_evidence":
            return {
                pathname: "/dashboard",
                query: {
                    view: "reportsubmissionevidence",
                    topic: flow.id,
                    category
                }
            };
        case "interpreter_guidance":
            return {
                pathname: "/dashboard/explorer",
                query: {
                    category,
                    topic: flow.id,
                    focus: "interpreter_guidance"
                }
            };
        case "quick_exit":
            return null;
    }
}
}),
"[project]/src/app/dashboard/page.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "default",
    ()=>DashboardPage
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-jsx-dev-runtime.js [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$dashboard$2f$dashboard$2d$home$2d$screen$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/components/dashboard/dashboard-home-screen.tsx [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$assistant$2d$categories$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/lib/assistant-categories.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$dashboard$2d$card$2d$flows$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/src/lib/dashboard-card-flows.ts [app-rsc] (ecmascript)");
;
;
;
;
async function DashboardPage({ searchParams }) {
    const resolved = await searchParams ?? {};
    const rawView = resolved.view;
    const rawFresh = resolved.fresh;
    const rawRecording = resolved.recording;
    const rawVoice = resolved.voice;
    const rawMessage = resolved.message;
    const rawPrefillMessage = resolved.prefillMessage;
    const rawReportId = resolved.reportId;
    const rawCategory = resolved.category;
    const rawTopic = resolved.topic;
    const view = Array.isArray(rawView) ? rawView[0] : rawView;
    const fresh = Array.isArray(rawFresh) ? rawFresh[0] : rawFresh;
    const recording = Array.isArray(rawRecording) ? rawRecording[0] : rawRecording;
    const voice = Array.isArray(rawVoice) ? rawVoice[0] : rawVoice;
    const message = Array.isArray(rawMessage) ? rawMessage[0] : rawMessage;
    const prefillMessage = Array.isArray(rawPrefillMessage) ? rawPrefillMessage[0] : rawPrefillMessage;
    const reportId = Array.isArray(rawReportId) ? rawReportId[0] : rawReportId;
    const categoryValue = Array.isArray(rawCategory) ? rawCategory[0] : rawCategory;
    const topicValue = Array.isArray(rawTopic) ? rawTopic[0] : rawTopic;
    const assistantRecording = recording === "1";
    const assistantVoiceMode = voice === "1";
    const assistantStartFresh = fresh === "1";
    const assistantCategory = (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$assistant$2d$categories$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["isAssistantIncidentCategory"])(categoryValue) ? categoryValue : undefined;
    const assistantTopic = (0, __TURBOPACK__imported__module__$5b$project$5d2f$src$2f$lib$2f$dashboard$2d$card$2d$flows$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["isDashboardCardFlowId"])(topicValue) ? topicValue : undefined;
    let homeView = "overview";
    if (view === "microeducation") {
        homeView = "microeducation";
    } else if (view === "resources") {
        homeView = "resources";
    } else if (view === "localintelligence") {
        homeView = "localintelligence";
    } else if (view === "smartdialler") {
        homeView = "smartdialler";
    } else if (view === "safetyplan") {
        homeView = "safetyplan";
    } else if (view === "microcards") {
        homeView = "microcards";
    } else if (view === "microcarddetail") {
        homeView = "microcarddetail";
    } else if (view === "assistantconversation") {
        homeView = "assistantconversation";
    } else if (view === "assistant") {
        homeView = "assistant";
    } else if (view === "scamshieldintake") {
        homeView = "scamshieldintake";
    } else if (view === "scamshieldrisk") {
        homeView = "scamshieldrisk";
    } else if (view === "scamshieldassets") {
        homeView = "scamshieldassets";
    } else if (view === "scamshieldagency") {
        homeView = "scamshieldagency";
    } else if (view === "reportshistory") {
        homeView = "reportshistory";
    } else if (view === "reportoverview") {
        homeView = "reportoverview";
    } else if (view === "reportsubmissionsupport") {
        homeView = "reportsubmissionsupport";
    } else if (view === "reportsubmissionrecommendations") {
        homeView = "reportsubmissionrecommendations";
    } else if (view === "reportsubmissionhistory") {
        homeView = "reportsubmissionhistory";
    } else if (view === "reportsubmissiondetailedexplanations") {
        homeView = "reportsubmissiondetailedexplanations";
    } else if (view === "reportsubmissiondetails") {
        homeView = "reportsubmissiondetails";
    } else if (view === "reportsubmissionevidence") {
        homeView = "reportsubmissionevidence";
    } else if (view === "reportsubmissionreview") {
        homeView = "reportsubmissionreview";
    } else if (view === "reportsubmissionshare") {
        homeView = "reportsubmissionshare";
    } else if (view === "reportsubmissionsuccess") {
        homeView = "reportsubmissionshare";
    }
    return /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$src$2f$components$2f$dashboard$2f$dashboard$2d$home$2d$screen$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["default"], {
        homeView: homeView,
        assistantStartFresh: assistantStartFresh,
        assistantRecording: assistantRecording,
        assistantVoiceMode: assistantVoiceMode,
        assistantMessage: message,
        assistantPrefillMessage: prefillMessage,
        reportId: reportId,
        assistantCategory: assistantCategory,
        assistantTopic: assistantTopic
    }, void 0, false, {
        fileName: "[project]/src/app/dashboard/page.tsx",
        lineNumber: 119,
        columnNumber: 5
    }, this);
}
}),
"[project]/src/app/dashboard/page.tsx [app-rsc] (ecmascript, Next.js Server Component)", ((__turbopack_context__) => {

__turbopack_context__.n(__turbopack_context__.i("[project]/src/app/dashboard/page.tsx [app-rsc] (ecmascript)"));
}),
"[externals]/next/dist/shared/lib/no-fallback-error.external.js [external] (next/dist/shared/lib/no-fallback-error.external.js, cjs)", ((__turbopack_context__, module, exports) => {

const mod = __turbopack_context__.x("next/dist/shared/lib/no-fallback-error.external.js", () => require("next/dist/shared/lib/no-fallback-error.external.js"));

module.exports = mod;
}),
];

//# sourceMappingURL=%5Broot-of-the-server%5D__69f83eb3._.js.map