// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/auth/callback" | "/dashboard" | "/dashboard/explorer" | "/dashboard/explorer/service-details" | "/dashboard/notifications" | "/dashboard/reports" | "/dashboard/reports/[reportId]" | "/dashboard/settings" | "/dashboard/settings/privacy-policy" | "/dashboard/settings/terms-conditions" | "/forgot-password" | "/guestbook" | "/login" | "/neutral" | "/privacy-policy" | "/profile" | "/register" | "/reset-password" | "/terms-conditions" | "/test-orb"
type PageRoutes = never
type LayoutRoutes = "/" | "/dashboard"
type RedirectRoutes = never
type RewriteRoutes = "/api/auth/[[...path]]" | "/api/v1/[[...path]]"
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/api/auth/[[...path]]": { "path"?: string[]; }
  "/api/v1/[[...path]]": { "path"?: string[]; }
  "/auth/callback": {}
  "/dashboard": {}
  "/dashboard/explorer": {}
  "/dashboard/explorer/service-details": {}
  "/dashboard/notifications": {}
  "/dashboard/reports": {}
  "/dashboard/reports/[reportId]": { "reportId": string; }
  "/dashboard/settings": {}
  "/dashboard/settings/privacy-policy": {}
  "/dashboard/settings/terms-conditions": {}
  "/forgot-password": {}
  "/guestbook": {}
  "/login": {}
  "/neutral": {}
  "/privacy-policy": {}
  "/profile": {}
  "/register": {}
  "/reset-password": {}
  "/terms-conditions": {}
  "/test-orb": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/dashboard": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
